### ISSUE TITLE
async with  webpack.

### ISSUE THREAD

**Issue by nonlux** [csstools/postcss-font-magician#44]
Given `font-magician` with asyns:
``` 
  magicianPostPlugin({
     async: path.resolve(BUILD_DIR, 'async_fonts.js'),
  }),
```
When I run webpack
Then I see error 
```
Module build failed: ModuleBuildError: Module build failed: Error: ENOENT: no such file or directory, open 'loader.min.js'
```

My fast fix to work:
```
      var asyncPath = options.async[0];
      var asyncJs = '(function(){' +
      fs.readFileSync(__dirname+'/loader.min.js', 'utf8') + 'loadFonts(' + JSON.stringify(fontFaces) + ')' +
                '})()';

      fs.writeFileSync(asyncPath, asyncJs);
```

I want to send PR, but I can't to understand  generation `asyncPath`.
Why options.async is array?
Why do you generate relative paths?

**Comment by MyNameReallySux** [comment]
Is this something that is still being looked into. Looks like there has been no update recently. Having the same issue.

**Comment by romainmenke** [comment]
I agree that this is an issue.

It doesn't make any sense to use the exact form of relative paths that this package uses for generated files. _I am fairly certain that all relative paths in this package are broken._

I've updated this so that it will use paths relative to the current working directory.

This will be released in `v4`.
