### ISSUE TITLE
Self-hosted Google fonts

### ISSUE THREAD

**Issue by ghost** [csstools/postcss-font-magician#72]
​

**Comment by igormartimiano** [comment]
You probably doesn't need it anymore but it theoretically can and use google fonts as fallback: https://github.com/jonathantneal/postcss-font-magician#hosted
Though I just couldn't make it work using gulp.. maybe with webpack: https://github.com/jonathantneal/postcss-font-magician/issues/75#issuecomment-485420009

**Comment by kdex** [comment]
@igormartimiano In fact, I'm still looking for a way to solve this, so I appreciate your effort, thanks.

I could have been more precise in describing what I wished `postcss-font-magician` did, so let me get a little more detailed:

`postcss-font-magician` should download the referenced Google _fonts files_ (e. g. `.woff`, `.woff2`, …) at _build time_. Right now, to the best of my knowledge, it only downloads Google's CSS code that, in turn, imports these font files from Google's servers at _run time_.

Another thing you can already do is that at build time, you can instruct `postcss-font-magician` to include local font files. So, assuming that you have `Roboto.woff2` stored in your repository, you could instruct `postcss-font-magician` to include it, too. This will import said font file from your own server at run time, without forcing your users' browsers to contact Google.

You could combine these two approaches and first manually download `Roboto.woff2` from Google, and then later, have `postcss-font-magician` include it by specifying the `Roboto.woff2` at build time.

What I wanted was a mix between the two approaches that allowed you to automate that, because font files are essentially blobs and don't belong into your project repository anyway. The idea was for `postcss-font-magician` to download all the font files needed for a given font face from Google and then include build-time references to them. This allows you to use Google fonts, but at no point will your users' machines be forced to contact Google.

For clarity's sake, `local()` in the font-face definition is not what I was referring to. It only allows you to save bandwidth by not forcing your users to download the font files at all if they already have the font installed on their system. That would have to be added to the `font-face` rule, too, but isn't my primary concern in this issue.

@jonathantneal: Out of curiosity, is there an intent/general interest to implement this? No pressure. :p

**Comment by igormartimiano** [comment]
Ohh I see, a bit more complex than I thought. I also think that would be a very helpful feature. 
By the way, that's exactly what I ended up doing manually last week as I only had one font to be included and wasn't much of a problem. I can see it easily being a hassle though in multiple projects or when you have a ton of different imported fonts.
+1 to that

**Comment by igormartimiano** [comment]
I see, a bit more complex than I thought. I also think that would be a very helpful feature.
By the way, that's exactly what I ended up doing manually last week as I only had one font to be included and wasn't much of a problem. I can see it easily being a hassle though in multiple projects or when you have a ton of different imported fonts.
+1 to that

**Comment by romainmenke** [comment]
Closing as the original post is gone 🤷
