### ISSUE TITLE
Hosted fonts doesn't work at all

### ISSUE THREAD

**Issue by RomkaLTU** [csstools/postcss-font-magician#75]
This doesn't work:

```
require('postcss-font-magician')({
   hosted: ['./src/assets/fonts/','/assets/fonts/'],
}),
```

Paths are good.

**Comment by TheDutchCoder** [comment]
Agreed, I can't make this work either.

Manually specifying font-face rules works fine, but the plugin itself seems to be broken when it comes to hosted fonts.

**Comment by alecnmk** [comment]
it does work, I was able to make it work by adding a file-loader (https://chriscourses.com/blog/loading-fonts-webpack for the reference)

**Comment by YyzclYang** [comment]
Agreed，when i use 
```js
module.exports = {
  plugins: [
    require("cssnano")({
      preset: "default"
    }),
    require("postcss-font-magician")({
      hosted: ["./assets/fonts"]
    }),
    require("autoprefixer")
  ]
};
```
and local font file doesn't work，and `style.css` haven't  `@font-face`

**Comment by thebrodmann** [comment]
looks like there is an error that may be related with this issue:

```
Error: EISDIR: illegal operation on a directory, read
```

**Comment by denizdogan** [comment]
I can't this to work either. I use Parcel, so I'm not configuring any loaders or anything like that, I just have .postcssrc and while there are no visible errors, it simply doesn't add any @font-face rules.

**Comment by JamesTheHacker** [comment]
Doesn't work for me with either:

```
module.exports = {
    plugins: [
      require('postcss-nested'),
      require('postcss-cssnext'),
      require('postcss-font-magician')({
        hosted: [ './assets/fonts' ]
     })
    ]
  }
```
Fonts are there.

**Comment by aviapic** [comment]
**It works with GULP. (certainly also for others ...)**

**You must know the "DECLARED" family font name of your font file !** (stupid but logical)

keep in mind, that this module extract all font names "DECLARED IN" fonts files,
and compare if one of them match the one you used in your css !

SO, make sure you use a "DECLARED" family font name , in your css ! 

In order to display the "DECLARED" font family name of your font file, do this :
in node_modules dependency : "directory-fonts-complete"
edit index.js and add at Line 85 : 
console.log(fontFamily);

Then run your gulp task, and check if you use the SAME font name in your css...
The console will display the DECLARED name of your font file !

**Example that will show the font name that you can't guess !**

try use "**The Bold Font**" downloaded on dafont.com ... [link](https://www.dafont.com/fr/the-bold-font.font)

the DECLARED font name of this font is: "**The**" !!!!

So
- first solution (not recommended):

in css use :
`body {font-family: "The";}`

OR
- second solution (prefered):

in css use :
`body {font-family: "The Bold Font";}`
and in postcss-font-magician add  option 'aliases'
```
require("postcss-font-magician")({
     hosted: ['./SRC/assets/font', '/assets/font'],
     aliases: {'The Bold Font': 'The'}
})
```
Hope it helps you (sorry for my english)

**Comment by romainmenke** [comment]
The `hosted` option does work.
But there are also issues upstream.
Please file an issue there if this is still causing issues : https://github.com/jonathantneal/directory-fonts-complete
