### ISSUE TITLE
Usage in Parcel

### ISSUE THREAD

**Issue by ghost** [csstools/postcss-font-magician#88]
Hi! I am learning PostCSS because I want to use it in a React project bundled by Parcel. I have added your plugin:

```
yarn add -D postcss-font-magician
```

And I have created a `.postcssrc`:

```
{
    "plugins": {
        "postcss-font-magician": {}
    }
}
```

It does seem to be working, because I am seeing the `font-family` from Google that I want in my project:

```
body {
  font-family: 'Noto Sans SC', sans-serif;
}
```

I would certainly appreciate some help to answer two questions:

- Is this all I need? Because `.prettierrc` is looking very different in my editor. It's as if `.postcssrc` isn't being recognised:

![image](https://user-images.githubusercontent.com/25172271/82737091-a3b1f400-9d04-11ea-9992-64a78a375ebf.png)

![image](https://user-images.githubusercontent.com/25172271/82737104-b62c2d80-9d04-11ea-886d-2ffca785870a.png)

- How will it be added during production build? Because it's installed as a devDependency.

**Comment by codebling** [comment]
Hi @mjfneto. This is probably the kind of question that should be posted on Stackoverflow, or another questions & answers site. GitHub Issues are generally used for reporting software bugs. 

I'll try to answer your questions here, nonetheless. 

> Is this all I need? 

Yes, that is all you need. Check your bundled CSS file, you should see that `@font-face` has been added.

> Because .prettierrc is looking very different in my editor. It's as if .postcssrc isn't being recognised

Whether or not your editor recognizes a file type has nothing to do with whether it works in Node. Set the file type for `.postcssrc` to JSON and you should get highlighting.

> How will it be added during production build? Because it's installed as a devDependency.

It won't be added to your production build. That's how Parcel works. `dependencies` lists packages needed for run-time, and `devDependencies` are packages needed before run-time or during development. Since Parcel only bundles files, it's a build step - it's not needed after that. Postcss is the same. 


Hope that helps.

**Comment by mjfneto** [comment]
Much obliged, @codebling.
